# Form implementation generated from reading ui file 'widget_graph.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GraphForm(object):
    def setupUi(self, GraphForm):
        GraphForm.setObjectName("GraphForm")
        GraphForm.resize(1024, 616)
        GraphForm.setStyleSheet("QWidget#GraphForm {\n"
"    background-color: rgb(89, 89, 89);\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(GraphForm)
        self.horizontalLayout.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_1 = QtWidgets.QFrame(parent=GraphForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_1.sizePolicy().hasHeightForWidth())
        self.frame_1.setSizePolicy(sizePolicy)
        self.frame_1.setMinimumSize(QtCore.QSize(700, 600))
        self.frame_1.setStyleSheet("QFrame#frame_1 {\n"
"    background-color: rgb(253, 253, 253);\n"
"    border-radius: 4px;\n"
"}")
        self.frame_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_1.setObjectName("frame_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graph_area = GLViewWidget(parent=self.frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_area.sizePolicy().hasHeightForWidth())
        self.graph_area.setSizePolicy(sizePolicy)
        self.graph_area.setStyleSheet("GLViewWidget#graph_area {\n"
"    border-radius: 3px;\n"
"}")
        self.graph_area.setObjectName("graph_area")
        self.button_graph_reset = QtWidgets.QPushButton(parent=self.graph_area)
        self.button_graph_reset.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        self.button_graph_reset.setFont(font)
        self.button_graph_reset.setStyleSheet("QPushButton {\n"
"    background-color: rgba(253, 253, 253,0);\n"
"    border: 0px solid;\n"
"}")
        self.button_graph_reset.setText("")
        self.button_graph_reset.setObjectName("button_graph_reset")
        self.horizontalLayout_2.addWidget(self.graph_area)
        self.horizontalLayout.addWidget(self.frame_1)
        self.frame_2 = QtWidgets.QFrame(parent=GraphForm)
        self.frame_2.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_2.setStyleSheet("QFrame#frame_2 {\n"
"    background-color: rgb(200, 200, 200);\n"
"    border-radius: 4px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.button_x = QtWidgets.QPushButton(parent=self.frame_2)
        self.button_x.setGeometry(QtCore.QRect(17, 17, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        self.button_x.setFont(font)
        self.button_x.setStyleSheet("QPushButton {\n"
"    background-color: rgb(253, 253, 253);\n"
"    border: 2px solid rgb(100, 100, 100);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #333;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: lightgray;\n"
"     border: 2px solid #000;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgb(200,200,200);\n"
"}")
        self.button_x.setObjectName("button_x")
        self.button_y = QtWidgets.QPushButton(parent=self.frame_2)
        self.button_y.setGeometry(QtCore.QRect(17, 79, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        self.button_y.setFont(font)
        self.button_y.setStyleSheet("QPushButton {\n"
"    background-color: rgb(253, 253, 253);\n"
"    border: 2px solid rgb(100, 100, 100);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #333;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: lightgray;\n"
"     border: 2px solid #000;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgb(200,200,200);\n"
"}")
        self.button_y.setObjectName("button_y")
        self.button_z = QtWidgets.QPushButton(parent=self.frame_2)
        self.button_z.setGeometry(QtCore.QRect(17, 141, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        self.button_z.setFont(font)
        self.button_z.setStyleSheet("QPushButton {\n"
"    background-color: rgb(253, 253, 253);\n"
"    border: 2px solid rgb(100, 100, 100);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #333;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: lightgray;\n"
"     border: 2px solid #000;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgb(200,200,200);\n"
"}")
        self.button_z.setObjectName("button_z")
        self.combo_x = QtWidgets.QComboBox(parent=self.frame_2)
        self.combo_x.setGeometry(QtCore.QRect(81, 16, 151, 28))
        self.combo_x.setStyleSheet("QComboBox {\n"
"    padding-left: 4px;\n"
"}")
        self.combo_x.setObjectName("combo_x")
        self.combo_y = QtWidgets.QComboBox(parent=self.frame_2)
        self.combo_y.setGeometry(QtCore.QRect(81, 78, 151, 28))
        self.combo_y.setStyleSheet("QComboBox {\n"
"    padding-left: 4px;\n"
"}")
        self.combo_y.setCurrentText("")
        self.combo_y.setObjectName("combo_y")
        self.combo_z = QtWidgets.QComboBox(parent=self.frame_2)
        self.combo_z.setGeometry(QtCore.QRect(81, 140, 151, 28))
        self.combo_z.setStyleSheet("QComboBox {\n"
"    padding-left: 4px;\n"
"}")
        self.combo_z.setObjectName("combo_z")
        self.combo_time = QtWidgets.QComboBox(parent=self.frame_2)
        self.combo_time.setGeometry(QtCore.QRect(81, 472, 151, 28))
        self.combo_time.setStyleSheet("QComboBox {\n"
"    padding-left: 4px;\n"
"}")
        self.combo_time.setObjectName("combo_time")
        self.button_time = QtWidgets.QPushButton(parent=self.frame_2)
        self.button_time.setGeometry(QtCore.QRect(17, 473, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        self.button_time.setFont(font)
        self.button_time.setStyleSheet("QPushButton {\n"
"    background-color: rgb(253, 253, 253);\n"
"    border-radius: 4px;\n"
"}")
        self.button_time.setObjectName("button_time")
        self.bar_time = QtWidgets.QSlider(parent=self.frame_2)
        self.bar_time.setEnabled(True)
        self.bar_time.setGeometry(QtCore.QRect(18, 503, 215, 20))
        self.bar_time.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.bar_time.setObjectName("bar_time")
        self.button_track = QtWidgets.QPushButton(parent=self.frame_2)
        self.button_track.setGeometry(QtCore.QRect(16, 221, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        self.button_track.setFont(font)
        self.button_track.setStyleSheet("QPushButton {\n"
"    background-color: rgb(253, 253, 253);\n"
"    border-radius: 4px;\n"
"}")
        self.button_track.setObjectName("button_track")
        self.combo_track = QtWidgets.QComboBox(parent=self.frame_2)
        self.combo_track.setGeometry(QtCore.QRect(80, 220, 151, 28))
        self.combo_track.setStyleSheet("QComboBox {\n"
"    padding-left: 2px;\n"
"}")
        self.combo_track.setObjectName("combo_track")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame_2)
        self.scrollArea.setGeometry(QtCore.QRect(16, 250, 211, 191))
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidget = QtWidgets.QWidget()
        self.scrollAreaWidget.setGeometry(QtCore.QRect(0, 0, 209, 189))
        self.scrollAreaWidget.setStyleSheet("QWidget#scrollAreaWidget {\n"
"    background-color: rgb(253, 253, 253);\n"
"    border-radius: 4px;\n"
"}")
        self.scrollAreaWidget.setObjectName("scrollAreaWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidget)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidget)
        self.lineEdit_x_min = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_x_min.setGeometry(QtCore.QRect(19, 46, 91, 21))
        self.lineEdit_x_min.setStyleSheet("QLineEdit {\n"
"    padding-left: 2px;\n"
"}")
        self.lineEdit_x_min.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_x_min.setObjectName("lineEdit_x_min")
        self.lineEdit_x_max = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_x_max.setGeometry(QtCore.QRect(135, 46, 91, 21))
        self.lineEdit_x_max.setStyleSheet("QLineEdit {\n"
"    padding-left: 2px;\n"
"}")
        self.lineEdit_x_max.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_x_max.setObjectName("lineEdit_x_max")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.frame_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(113, 42, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("QPlainTextEdit {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.plainTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.plainTextEdit.setUndoRedoEnabled(False)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(parent=self.frame_2)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(113, 104, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setStyleSheet("QPlainTextEdit {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.plainTextEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.plainTextEdit_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.plainTextEdit_2.setUndoRedoEnabled(False)
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.lineEdit_y_max = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_y_max.setGeometry(QtCore.QRect(135, 108, 91, 21))
        self.lineEdit_y_max.setStyleSheet("QLineEdit {\n"
"    padding-left: 2px;\n"
"}")
        self.lineEdit_y_max.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_y_max.setObjectName("lineEdit_y_max")
        self.lineEdit_y_min = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_y_min.setGeometry(QtCore.QRect(19, 108, 91, 21))
        self.lineEdit_y_min.setStyleSheet("QLineEdit {\n"
"    padding-left: 2px;\n"
"}")
        self.lineEdit_y_min.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_y_min.setObjectName("lineEdit_y_min")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(parent=self.frame_2)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(113, 166, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.plainTextEdit_5.setFont(font)
        self.plainTextEdit_5.setStyleSheet("QPlainTextEdit {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.plainTextEdit_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.plainTextEdit_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.plainTextEdit_5.setUndoRedoEnabled(False)
        self.plainTextEdit_5.setReadOnly(True)
        self.plainTextEdit_5.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.lineEdit_z_max = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_z_max.setGeometry(QtCore.QRect(135, 170, 91, 21))
        self.lineEdit_z_max.setStyleSheet("QLineEdit {\n"
"    padding-left: 2px;\n"
"}")
        self.lineEdit_z_max.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_z_max.setObjectName("lineEdit_z_max")
        self.lineEdit_z_min = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_z_min.setGeometry(QtCore.QRect(19, 170, 91, 21))
        self.lineEdit_z_min.setStyleSheet("QLineEdit {\n"
"    padding-left: 2px;\n"
"}")
        self.lineEdit_z_min.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_z_min.setObjectName("lineEdit_z_min")
        self.button_time_play = QtWidgets.QPushButton(parent=self.frame_2)
        self.button_time_play.setGeometry(QtCore.QRect(18, 528, 25, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.button_time_play.setFont(font)
        self.button_time_play.setStyleSheet("QPushButton {\n"
"    background-color: rgb(253, 253, 253);\n"
"    border: 2px solid rgb(100, 100, 100);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #333;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: lightgray;\n"
"     border: 2px solid #000;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgb(200,200,200);\n"
"}")
        self.button_time_play.setObjectName("button_time_play")
        self.button_time_speed = QtWidgets.QPushButton(parent=self.frame_2)
        self.button_time_speed.setGeometry(QtCore.QRect(46, 528, 28, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        self.button_time_speed.setFont(font)
        self.button_time_speed.setStyleSheet("QPushButton {\n"
"    background-color: rgb(253, 253, 253);\n"
"    border: 2px solid rgb(100, 100, 100);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #333;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: lightgray;\n"
"     border: 2px solid #000;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgb(200,200,200);\n"
"}")
        self.button_time_speed.setObjectName("button_time_speed")
        self.plainTextEdit_timestamp = QtWidgets.QPlainTextEdit(parent=self.frame_2)
        self.plainTextEdit_timestamp.setGeometry(QtCore.QRect(90, 515, 141, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_timestamp.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_timestamp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.plainTextEdit_timestamp.setFont(font)
        self.plainTextEdit_timestamp.setStyleSheet("QPlainTextEdit {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: 0px;\n"
"}")
        self.plainTextEdit_timestamp.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.plainTextEdit_timestamp.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.plainTextEdit_timestamp.setUndoRedoEnabled(False)
        self.plainTextEdit_timestamp.setReadOnly(True)
        self.plainTextEdit_timestamp.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.plainTextEdit_timestamp.setObjectName("plainTextEdit_timestamp")
        self.horizontalLayout.addWidget(self.frame_2)

        self.retranslateUi(GraphForm)
        QtCore.QMetaObject.connectSlotsByName(GraphForm)

    def retranslateUi(self, GraphForm):
        _translate = QtCore.QCoreApplication.translate
        GraphForm.setWindowTitle(_translate("GraphForm", "Form"))
        self.button_x.setText(_translate("GraphForm", "x-axis"))
        self.button_y.setText(_translate("GraphForm", "y-axis"))
        self.button_z.setText(_translate("GraphForm", "z-axis"))
        self.button_time.setText(_translate("GraphForm", "time"))
        self.button_track.setText(_translate("GraphForm", "track #"))
        self.plainTextEdit.setPlainText(_translate("GraphForm", "~"))
        self.plainTextEdit_2.setPlainText(_translate("GraphForm", "~"))
        self.plainTextEdit_5.setPlainText(_translate("GraphForm", "~"))
        self.button_time_play.setText(_translate("GraphForm", "▶"))
        self.button_time_speed.setText(_translate("GraphForm", "1.0x"))
        self.plainTextEdit_timestamp.setPlainText(_translate("GraphForm", "00:00:00/14:30:55"))
from pyqtgraph.opengl import GLViewWidget
